all:
  hosts:
    blackfalcon:
  children:
    personal:
      hosts:
        blackfalcon:
        bluefalcon:
    virtualmachines:
      hosts:
        ha:
        slu:
        biogen:
    servers:
      hosts:
        omv:
    dstservers:
      hosts:
        bw.datainscience.com:
        ftp.datainscience.com:
    biogenservers:
      hosts:
        pilothead01.hpc.biogen.com:
