session_name: hass
start_directory: /home/akail
windows:
  - window_name: main
    layout: main-vertical
    options:
      main-pane-width: 160
    panes:
      - shell_command:
        - cd ~/Projects/homeassistant
        - clear
      - shell_command:
        - cd /mnt/hass/config
        - clear
      - shell_command:
        - ssh hass
